In [2]:
# Introduction to Numpy ===>>>> 

# Numpy is an open-source library that is used for scitific calculations . 

# Why Numpy is better than List ? 
# (1). Homogenous data type 
# (2). Fast  Execution time 
# (3). Less consume memory 

In [6]:
import numpy as np 

In [7]:
a = [1,45,78,90]
type(a) 

list

In [9]:
b = np.array(a) 
b

array([ 1, 45, 78, 90])

In [11]:
type(b) 

numpy.ndarray

In [13]:
p = [[1,2,3] , [4,5,6] , [7,8,9]]
p

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
q = np.array(p) 
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
type(q) 

numpy.ndarray

In [19]:
print("Total Elements = " , q.size)  ## size = row*column 
print("Total Rows and columns = " , q.shape) ## shape = row , column 
print("Total Dimension =" , q.ndim)   ### ndim stands for  dimension of data . 

Total Elements =  9
Total Rows and columns =  (3, 3)
Total Dimension = 2


## How can we create a user defined Array ? 

In [21]:
a = [] 
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter item:"))
    a.append(val) 
# print(a) 
b = np.array(a) 
b

Enter size: 2
Enter item: 45
Enter item: 45


array([45, 45])

In [22]:
# Images ===> Pixels = 0(Black)-255px(white) ===> Normalize===> 0(Black)-1px
# (white) 
# Gradient Descent Optimization technique  ===> random weights and bias 
# When we have less data into our dataframe then we can add dummy data entries 
# using numpy . 

In [23]:
# Matrix  ===> row , column 
# Symmatric Matrix ===> n(rows) = n(columns) 
# Asymmatric Matrix ===> n(rows) != n(columns) 
# Digonal Elements ===> [(1,1) , (2,2) , (3,3) , (4,4)......(n,n)] 

In [24]:
# (1). zeros() ===> It will create an array in which all the
# values wil be zero and will be separated by .,

In [26]:
a = np.zeros(4) 
a

array([0., 0., 0., 0.])

In [28]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# (2). ones() ===> It will create an array in which all the values will be 1 . 

In [32]:
a = np.ones(4) 
a

array([1., 1., 1., 1.])

In [34]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# (3). eye() ===> 
# This will create an array in which digonal positional elements 
# will be one and rest all are 0.

In [38]:
a = np.eye(3,4)  ### Asymmatric Matrix 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
a = np.eye(4)  ### Symmatric Matrix 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
# diag() ==> We can set our custom values on the digonal position in a matrix . 

In [43]:
a = np.diag([1,34,67,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [45]:
# Random Module ====> 
# (1). Randint() ===> np.random.randint(min_number , max_number , total_numbers)
# (2). Rand() ====> np.random.rand(total numbers)
# (3). Randn() ===> np.random.randn(total numbers)
# (4). seed() ====> np.random.seed(pass the argument) 

In [47]:
np.random.randint(1,10,3)

array([3, 4, 4])

In [49]:
np.random.rand(5) 

array([0.7538544 , 0.9641784 , 0.32907335, 0.98093351, 0.19657359])

In [51]:
np.random.randn(4)

array([-1.87106816, -0.1324224 , -1.65431635, -0.72335392])

In [53]:
np.random.seed(70) 

np.random.randint(1,10,3)

array([7, 3, 9])

In [54]:
# Reshaping the data ===> 

# n(rows) * n(columns) = n(total_elements) 


In [56]:
# total = 12 
# 1*12 , 12*1 
# 2*6 , 6*2 
# 3*4 , 4*3 


In [58]:
a = np.random.randint(1,50,12)
a

array([16, 42, 14, 27, 22, 48, 35, 16, 11, 43, 12, 30])

In [60]:
a.reshape(2,6)

array([[16, 42, 14, 27, 22, 48],
       [35, 16, 11, 43, 12, 30]])

In [62]:
a.reshape(6,2)

array([[16, 42],
       [14, 27],
       [22, 48],
       [35, 16],
       [11, 43],
       [12, 30]])

In [64]:
a.reshape(3,4)

array([[16, 42, 14, 27],
       [22, 48, 35, 16],
       [11, 43, 12, 30]])

In [65]:
# View vs Copy 

In [67]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6]
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [69]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy() 
b[:] = 0 
a
b

array([0, 0, 0])

# Condtional Selection in Numpy 

In [71]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [75]:
b = a>10 
a[b]

array([11, 12, 13, 14, 15])

In [77]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [79]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [81]:
# LinSpace() ===> 
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [83]:
# hstack() and vstack() =====> 
a=  np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [85]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])